### ISSUE TITLE
какой пароль?

### ISSUE THREAD

**Issue by Hanni-afk** [TheC0mpany/NjRat-0.7D-Green-Edition-by-im523#1]

**Comment by TheC0mpany** [comment]
It doesn't have password

**Comment by ooo-sanya-pidor** [comment]
> _No description provided._

Зачем пароль, когда есть корпорация, которая борится с массовой диградацией сань во всём мире ? Заходи на сайт [http://sanya-pidor.ga](http://sanya-pidor.ga) . Открытия 5 декабря!
