### ISSUE TITLE
WinMM.Net Error

### ISSUE THREAD

**Issue by fandercompany** [TheC0mpany/NjRat-0.7D-Green-Edition-by-im523#15]
Displays a library no-go error, adds the program folder and the System32 folder. The error continues, how to solve the problem?
`"WinMM.Net, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"
   в NJRAT.Form1.Form1_Load(Object sender, EventArgs e)
   в System.EventHandler.Invoke(Object sender, EventArgs e)
   в System.Windows.Forms.Form.OnLoad(EventArgs e)
   в System.Windows.Forms.Form.OnCreateControl()
   в System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   в System.Windows.Forms.Control.CreateControl()
   в System.Windows.Forms.Control.WmShowWindow(Message& m)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   в System.Windows.Forms.ContainerControl.WndProc(Message& m)
   в System.Windows.Forms.Form.WmShowWindow(Message& m)
   в System.Windows.Forms.Form.WndProc(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

**Comment by LetachiFeree** [comment]
why do you need to solve the rat problem if you don't even have a clue how to install the library? Your thinking is like that of a russian teenager who does not know how to do anything except copy and put up for sale goods 10 years ago.
My advice to you is just don't take on a job you're not sure about.
