### ISSUE TITLE
Accidentally ran my own test stub

### ISSUE THREAD

**Issue by AAAqqqwe** [TheC0mpany/NjRat-0.7D-Green-Edition-by-im523#3]
Hey, I accidentally ran my own test stub by mistake, how do I delete it from my own machine?

**Comment by 0x0403** [comment]
> Hey, I accidentally ran my own test stub by mistake, how do I delete it from my own machine?

lmao fucking retard u dont

**Comment by AAAqqqwe** [comment]
lmao its alr fixed thanks for being a dick
