### ISSUE TITLE
I'm Unable to Open it

### ISSUE THREAD

**Issue by rama-spec** [TheC0mpany/NjRat-0.7D-Green-Edition-by-im523#4]
Hi There.
I'm Ramakrishna, I'm very beginner in cyber security.
So, I don't know how to run it..
I've installed it in Kali Linux and now I don't know how to run your program..
It will be better if you allot usage coloumn also in it with the Code..

Thankyou...

**Comment by TheC0mpany** [comment]
I do not code that, that was made by im523.
I just reupload it because a lot of people bind that with viruses.
That program was made for Windows 7-10
If you need a source code https://github.com/AliBawazeEer/RAT-NjRat-0.7d-modded-source-code
